services:
  redis:
    build:
      context: ./redis
    container_name: correctomatic-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD_HASH=${REDIS_PASSWORD_HASH}
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  redis-insight:
    image: redis/redisinsight
    container_name: correctomatic-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    # I don't know how to initialize the connection data
    # You should enter the connection data manually in the web interface

  dashboard:
    image: igrek8/bullmq-dashboard
    container_name: correctomatic-dashboard
    ports:
      - "3000:3000"
    # TO-DO: this image doesn't addmit setting a user
    command: [
      "--redis-host", "redis",
      "--bullmq-prefix", "bull",
      "--redis-password", "papaya"
      ]

volumes:
  redisinsight:   # Connection data is saved here
  redis_data:     # For persisting bullmq data
