services:
  redis:
    build:
      context: ./redis
    container_name: correctomatic-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD_HASH=${REDIS_PASSWORD_HASH}

  redis-insight:
    image: redis/redisinsight
    container_name: correctomatic-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    # I don't know how to initialize the connection data
    # You should enter the connection data manually in the web interface

  dashboard:
    image: igrek8/bullmq-dashboard
    container_name: correctomatic-dashboard
    ports:
      - "3000:3000"
    # TO-DO: this image doesn't addmit setting a user
    command: [
      "--redis-host", "redis",
      "--bullmq-prefix", "bull",
      "--redis-password", "papaya"
      ]

  # bullboard:
  #   container_name: bullboard
  #   # image: deadly0/bull-board # This one is too old
  #   image: venatum/bull-board # Doesn't seem to work
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=papaya
  #     - BULL_PREFIX=bull

volumes:
  redisinsight:
