services:
  redis:
    build:
      context: ./redis
    environment:
      - REDIS_PASSWORD_HASH=${REDIS_PASSWORD_HASH}
    ports:
      - "6379:6379"

  dashboard:
    image: igrek8/bullmq-dashboard
    ports:
      - "3000:3000"
    # TO-DO: this image doesn't addmit setting a user
    command: [
      "--redis-host", "redis",
      "--bullmq-prefix", "bull",
      "--redis-password", "papaya"
      ]
