services:
  redis:
    image: redis:7
    container_name: correctomatic-redis
    # Sets the password for the redis server and
    # enables the appendonly mode
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight
    container_name: correctomatic-redisinsight
    ports:
      - "5540:5540"
    # I don't know how to initialize the connection data
    # You should enter the connection data manually in the web interface,
    # so I've created a volume to persist the data
    volumes:
      - redisinsight:/data


  dashboard:
    image: igrek8/bullmq-dashboard
    container_name: correctomatic-dashboard
    ports:
      - "3000:3000"
    # TO-DO: this image doesn't addmit setting a user
    command: [
      "--redis-host", "redis",
      "--bullmq-prefix", "bull",
      "--redis-password", "${REDIS_PASSWORD}"
      ]

volumes:
  redisinsight:   # Connection data is saved here
  redis_data:     # For persisting bullmq data
