services:
  redis:
    build:
      context: ./redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  # redis:
  #   image: redis:7.2-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
